### ISSUE TITLE
Could you add `snake_case` and `kebab-case` transforms?

### ISSUE THREAD

**Issue by scillidan** [EhsanKia/Keypirinha-PuzzTools#1]
Like this:
```py
_TRANSFORMS = {
	...
	'kebabcase': lambda x: x.lower().replace('\s', '-'),
	'snakecase': lambda x: x.lower().replace('\s', '_'),
}
```

I like it, this dreamy tool faster than any other method I've used 🚀.
And elegant 🧐.

**Comment by EhsanKia** [comment]
Done! Try out the new version and see if it works as expected. Used a slightly better regex that also converts from `camelCase` into `camel_case` or `camel-case`

**Comment by scillidan** [comment]
It works well. Thanks, dude!
